Repository retaildevcrews/aks-secure-baseline-hack-template, pull requests merged in 2021-05, with the labels that each got.

#229 use Codespace secret for Azure tenant ID
  README.md
  setup.sh
Labels: Documentation, Sharing

#234 added Hack Guide
  docs/EngineeringPractices.md
  docs/HackGuide.md
  docs/NamingConvention.md
  docs/WorkingAgreement.md
Labels: Documentation, OCW, Sharing

#233 deploy to any region
  README.md
  cleanup.sh
  gitops/README.md
  gitops/baseline/cluster-baseline-settings/01-namespace.yaml
  gitops/cluster-baseline-settings/03-akv-secrets-store-csi.yaml
  gitops/cluster-baseline-settings/04-aad-pod-identity.yaml
  gitops/cluster-baseline-settings/05-kured.yaml
  gitops/kube-system/azm-agent-config.yaml
  gitops/namespaces.yaml
  networking/hub-regionA.json
  setup.sh
  templates/cluster-stamp.json
  templates/traefik-config.yaml
Labels: Bug, OCW, Sharing

#222 Updated Codespaces
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/post-install.sh
Labels: InternalFeedback, OCW, Sharing

#246 Added ghcr.io to registry pull list
  networking/hub-regionA.json
  templates/cluster-stamp.json
Labels: Bug

#255 Remove access policy from shared key vault before deleting managed identity
  cleanup.sh
Labels: OCW
