Repository retaildevcrews/aks-secure-baseline-hack-template, pull requests merged in 2021-06, with the labels that each got.

#251 use Codespaces secrets for certs
  README-AIRS.md
  README.md
  airs-cleanup.sh
  airs-setup.sh
  cluster-stamp.json
  docs/HackGuide.md
  setup.sh
  templates/traefik-config.yaml
Labels: AIRS, Sharing

#261 Add log/monitoring details for firewall and NSG to challenges
  README.md
  challenges/README.md
  challenges/blocked-traffic-dashboard/README.md
Labels: Spark

#316 update setup.sh to use codespace secrets for certs
  airs-setup.sh
  cleanup.sh
  setup.sh
Labels: InternalFeedback, Spark

#317 removed apt upgrade for speed
  .devcontainer/post-install.sh
Labels: DevExperience, Spark

#321 Add links to asb videos from upskilling hack to the hack guide
  docs/HackGuide.md
Labels: Documentation, Sharing

#343 Added Spark challenges
  challenges/azure-container-registry/README.md
  challenges/azure-container-registry/ngsa-ghcr.yaml
  challenges/deploy-WebV/README.md
  challenges/deploy-WebV/images/log-analytics-1.PNG
Labels: Challenge, Spark

#345 Enforce team name constraints
  airs-setup.sh
  setup.sh
Labels: InternalFeedback
