Repository retaildevcrews/aks-secure-baseline-hack-template, pull requests merged in 2021-07, with the labels that each got.

#352 updated codespaces from asb-spark
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/post-install.sh
Labels: InternalFeedback, Setup, Spark

#370 Spark feedback
  docs/HackGuide.md
Labels: InternalFeedback, Spark

#377 Add networking hub-regionA to delta folder with targetFqdns, ghcr, re…
  delta/networking/hub-regionA.json
Labels: Challenge

#378 merge asb-spark changes
  .devcontainer/devcontainer.json
  README-AIRS.md
  challenges/blocked-traffic-dashboard/README.md
  challenges/deploy-WebV/README.md
  challenges/redirect-http-to-https/README.md
  docs/HackGuide.md
  hack/.github/CODEOWNERS
  hack/.github/workflows/README.md
  hack/.github/workflows/create-dns-record.sh
  hack/.github/workflows/dns.yml
  hack/README.md
  hack/airs-cleanup.sh
  hack/airs-setup.sh
  hack/cluster-stamp.json
  hack/docs/cloudshell.txt
  hack/gitops/cluster-baseline-settings/01-namespace.yaml
  hack/gitops/ingress/01-namespace.yaml
  hack/gitops/ngsa/ngsa-memory.yaml
  hack/networking/hub-default.json
  hack/networking/hub-regionA.json
  hack/networking/spoke-BU0001A0008.json
Labels: AIRS, InternalFeedback, Spark, TechnicalDebt

#379 more asb-spark merges
  .github/CODEOWNERS
  .github/workflows/README.md
  .github/workflows/create-dns-record.sh
  .github/workflows/dns.txt
  README.md
  cleanup.sh
  cluster-stamp.json
  deploy/README.md
  deploy/cleanup.sh
  deploy/cluster-stamp.json
  deploy/gitops/ngsa/ngsa-memory.yaml
  deploy/networking/hub-regionA.json
  deploy/networking/spoke-BU0001A0008.json
  deploy/setup.sh
  docs/HackGuide.md
  docs/NamingConvention.md
  gitops/cluster-baseline-settings/01-namespace.yaml
  gitops/ingress/01-namespace.yaml
  gitops/namespaces.yaml
  gitops/ngsa/ngsa-memory.yaml
  hack/README.md
  hack/airs-setup.sh
  hack/docs/cloudshell.txt
  hack/networking/hub-default.json
  networking/hub-regionA.json
  networking/spoke-BU0001A0008.json
Labels: AIRS, Spark, TechnicalDebt

#383 Minor updates to README
  README.md
Labels: Documentation
